version: '3'
services:
  tf_mysql_server:
    image: mysql:8.0
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=task_flow
      - MYSQL_USER=hui
      - MYSQL_PASSWORD=123456
    volumes:
      - /opt/hui/projects/TaskFlow/data/mysql/data:/var/lib/mysql
      - /opt/hui/projects/TaskFlow/data/mysql/conf:/etc/mysql/conf.d
      - /opt/hui/projects/TaskFlow/data/mysql/log:/var/log/mysql

  tf_web:
    image: nginx:stable-alpine
    ports:
      - "6969:6969"
    volumes:
      - /opt/hui/projects/TaskFlow/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/hui/projects/TaskFlow/data/nginx/data:/data
      - /opt/hui/projects/TaskFlow/data/nginx/log:/var/log/nginx

  tf_api:
    image: taskflow_image
    ports:
      - "8099:8099"
    volumes:
      - /opt/hui/projects/TaskFlow/logs:/app/logs
      - /opt/hui/projects/TaskFlow/settings:/app/src/settings

    command: python main.py
    network_mode: host
    depends_on:
      - tf_mysql_server